import { content, type Content, type Lang } from "./content"

type AnyObject = Record<string, any>
function merge(base: AnyObject, updates: AnyObject): AnyObject {
  const result = { ...base }
  for (const [key, value] of Object.entries(updates)) {
    result[key] = value && typeof value === "object" && !Array.isArray(value)
      ? merge(result[key] ?? {}, value)
      : value
  }
  return result
}

const enPatch = {
  hero: { kicker: "BuildArena 2.0 · Season 02", season: "Season 2 · Of Course I Still Love You", subtitle: "The closed-loop engineering arena.", notice: "Build. Fly. Observe. Improve.", ctaPrimary: "Enter Season 02" },
  season: { tag: "// 01 — Season 02", title: 'Season 2\n"Of Course I Still Love You"', dates: "TBA – TBA AOE", briefTitle: "The Mission", brief: "Getting to orbit was just the warm-up. Now bring the machine home. Your agent designs the vehicle, builds it, writes the controller, launches the simulation, watches telemetry, diagnoses failures, changes the design, and tries again.", hooksTitle: "The S02 Loop", hooks: [{ title: "Agent Control", body: "The agent writes the controller and owns the simulation loop." }, { title: "Live Telemetry", body: "Each run produces evidence for the next engineering decision." }, { title: "Iterative Design", body: "Failures are feedback: change the design and try again." }] },
  tracks: { tag: "// 02 — Tracks", title: "Choose Your Engineering Loop", intro: "Season 02 is about closed-loop engineering: design, build, control, observe, diagnose, and improve.", note: "The main S02 loop is agent-controlled. Do not describe the run as manually driven.", items: [{ name: "Build with Agent", badge: "Main track", badgeVariant: "default", tagline: "Hand over the controls.\nLet your agent close the loop.", rules: ["The agent designs and builds the vehicle through the BuildArena MCP.", "The agent writes the controller and launches the simulation.", "Telemetry and run outcomes are used to diagnose and improve the design.", "Document the iterations and submit the evidence for the complete loop."] }, { name: "Human Boss Challenge", badge: "Showcase", badgeVariant: "accent", tagline: "Human engineering showcase.\nSee the rules for eligibility.", rules: ["Follow the official S02 rules for the human showcase.", "Submit a reproducible machine, run record, and writeup.", "Do not conflate this showcase with the agent-controlled main track."] }] },
  how: { tag: "// 03 — Closed Loop", title: "Build. Fly. Observe. Improve.", intro: "A Season 02 run is a closed engineering loop, not a manually driven one-shot flight.", phases: [{ key: "prepare", label: "Prepare", steps: [{ n: "01", title: "Design the vehicle", body: "Define the mission, vehicle, controller, and success signals." }, { n: "02", title: "Build via MCP", body: "The agent constructs the machine through the BuildArena MCP." }] }, { key: "compete", label: "Run the loop", steps: [{ n: "03", title: "Write the controller", body: "The agent writes the controller and launches the simulation." }, { n: "04", title: "Observe & improve", body: "Watch telemetry, diagnose failures, change the design, and try again." }] }, { key: "submit", label: "Submit", steps: [{ n: "05", title: "Submit the evidence", body: "Submit the machine, controller, telemetry, iteration history, and writeup." }] }], gameKeyCta: "", submitBodyForm: "Submit the machine, controller, telemetry, iteration history, and writeup.", repoCta: "Download BuildArena 2.0", cta: "Submit on Kaggle" },
  scoring: { tag: "// 04 — Scoring", title: "Official S02 Scoring", intro: "The displayed score must follow the official Season 02 scoring rules. No unsupported weights or formulas are shown here.", performanceTitle: "Rule-defined performance", performance: [{ name: "Official S02 metric", weight: "TBA", body: "See the Kaggle S02 Rules page for the authoritative metric, weights, normalization, and edge-case handling." }], costTitle: "Rule-defined cost", cost: [{ name: "Official S02 cost", body: "No local estimate is substituted for the official rule." }], formulaLabel: "Authoritative source", formulas: [{ label: "S02 Rules", value: "See Kaggle Rules — no unsupported formula" }], finalTitle: "Final score", finals: [{ label: "Status", value: "Defined by the official S02 scorer" }], tokenNote: "Scoring details are intentionally not invented here; the Kaggle S02 Rules and released scorer are authoritative." },
  submission: { tag: "// 05 — Submission & Validation", title: "Show the Complete Loop", intro: "Submit the machine, controller, telemetry, iteration history, and a clear account of how the agent improved the design.", deliverablesTitle: "Build with Agent deliverables", deliverables: ["machine.bsg", "controller code", "telemetry / trajectory CSV", "iteration history", "chat / workflow record", "Kaggle writeup and video"], humanTitle: "Human Boss deliverables", humanDeliverables: ["human-built machine", "run record", "Kaggle writeup and video"], validationTitle: "S02 Validation Rules", validations: [{ q: "Closed-loop evidence", a: "The submitted record must show the agent design, controller, simulation, telemetry, diagnosis, and iteration process." }, { q: "Controller integrity", a: "The controller must be included and run through the declared simulation process." }, { q: "Telemetry evidence", a: "Claims about improvement must be supported by valid telemetry and documented attempts." }, { q: "No fabricated evidence", a: "Do not materially manipulate machine files, telemetry, or workflow records." }], reviewTitle: "Official Review", review: ["Complete submissions enter the provisional showcase.", "Award candidates undergo machine, controller, telemetry, and workflow review.", "Only verified entries receive official awards."], ctaRules: "Read S02 rules", ctaSubmit: "Submit on Kaggle" },
  leaderboard: { tag: "// 07 — Leaderboard", title: "Season 02 Leaderboard", status: "Opening soon", emptyTitle: "The loop is warming up", emptyBody: "Build, fly, observe, improve — then submit your best verified loop." },
  awards: { tag: "// 06 — Awards", title: "Season 02 Awards", pool: { label: "Season 02 prize pool", amount: "$3,000", unit: "/ season" }, main: [{ name: "Season 02 Awards", body: "Award structure and eligibility follow the official S02 Rules.", badge: "See official rules", prize: "TBA" }], titles: [{ name: "Verified S02 Build", body: "Recognition is subject to the official review process.", prize: "TBA" }], community: [{ name: "S02 Showcase", prize: "See rules" }] },
  faq: { tag: "// 08 — FAQ", title: "Season 02 FAQ", items: [{ q: "Is Season 02 manually driven?", a: "No. The main S02 concept is agent-controlled closed-loop engineering: the agent writes the controller, launches simulation, watches telemetry, diagnoses failures, changes the design, and tries again." }, { q: "What is scored?", a: "Only the official S02 Rules and released scorer define the score. This site does not invent weights or formulas." }, { q: "Where do I submit?", a: "On Kaggle. This site is informational only." }] },
  cta: { title: "Ready to close\nthe engineering loop?", button: "Enter Season 02" },
}

const zhPatch = {
  hero: { kicker: "BuildArena 2.0 · 第二赛季", season: "第二赛季 · Of Course I Still Love You", subtitle: "闭环工程竞技场。", notice: "建造 · 飞行 · 观察 · 改进", ctaPrimary: "进入第二赛季" },
  season: { tag: "// 01 — 第二赛季", title: "第二赛季\n「Of Course I Still Love You」", dates: "待定 – 待定 AOE", briefTitle: "赛题", brief: "成功入轨只是热身。现在，把机器带回家。你的 agent 负责设计载具、完成建造、编写控制器、启动仿真、观察 telemetry、诊断失败、修改设计并再次尝试。", hooksTitle: "第二赛季闭环", hooks: [{ title: "Agent 控制", body: "控制器与仿真闭环由 agent 负责。" }, { title: "实时 Telemetry", body: "每次运行都为下一次工程决策提供证据。" }, { title: "迭代设计", body: "失败就是反馈：修改设计，再次尝试。" }] },
  tracks: { tag: "// 02 — 赛道", title: "选择你的工程闭环", intro: "第二赛季的核心是闭环工程：设计、建造、控制、观察、诊断与改进。", note: "第二赛季主赛道由 agent 控制，不应描述为人工驾驶。", items: [{ name: "Build with Agent", badge: "主赛道", badgeVariant: "default", tagline: "把控制权交给 agent。\n完成完整闭环。", rules: ["agent 通过 BuildArena MCP 设计并建造载具。", "agent 编写控制器并启动仿真。", "使用 telemetry 和运行结果诊断并改进设计。", "记录迭代并提交完整闭环证据。"] }, { name: "Human Boss Challenge", badge: "展示赛道", badgeVariant: "accent", tagline: "人类工程展示。\n资格以官方规则为准。", rules: ["遵守第二赛季人类展示赛道规则。", "提交可复现机器、运行记录与说明。", "不要将该展示赛道与 agent 主赛道混为一谈。"] }] },
  how: { tag: "// 03 — 闭环流程", title: "建造 · 飞行 · 观察 · 改进", intro: "第二赛季是闭环工程，不是人工驾驶的一次性飞行。", phases: [{ key: "prepare", label: "准备", steps: [{ n: "01", title: "设计载具", body: "定义任务、载具、控制器与成功信号。" }, { n: "02", title: "通过 MCP 建造", body: "由 agent 通过 BuildArena MCP 完成机器建造。" }] }, { key: "compete", label: "运行闭环", steps: [{ n: "03", title: "编写控制器", body: "由 agent 编写控制器并启动仿真。" }, { n: "04", title: "观察并改进", body: "观察 telemetry、诊断失败、修改设计，再次尝试。" }] }, { key: "submit", label: "提交", steps: [{ n: "05", title: "提交证据", body: "提交机器、控制器、telemetry、迭代历史与说明。" }] }], gameKeyCta: "", submitBodyForm: "提交机器、控制器、telemetry、迭代历史与说明。", repoCta: "下载 BuildArena 2.0", cta: "前往 Kaggle 提交" },
  scoring: { tag: "// 04 — 评分", title: "官方第二季评分", intro: "页面只显示官方第二季评分规则，不再添加没有依据的权重或公式。", performanceTitle: "以规则定义的表现", performance: [{ name: "官方第二季指标", weight: "待定", body: "具体指标、权重、归一化与边界情况以 Kaggle 第二季 Rules 页面为准。" }], costTitle: "以规则定义的成本", cost: [{ name: "官方第二季成本", body: "不使用本地估算替代官方规则。" }], formulaLabel: "权威来源", formulas: [{ label: "第二季 Rules", value: "以 Kaggle Rules 为准，不展示无依据公式" }], finalTitle: "最终成绩", finals: [{ label: "状态", value: "由官方第二季评分器定义" }], tokenNote: "这里不臆造评分细节；Kaggle 第二季 Rules 与正式评分器是唯一权威来源。" },
  submission: { tag: "// 05 — 提交与校验", title: "展示完整闭环", intro: "提交机器、控制器、telemetry、迭代历史，并清楚说明 agent 如何改进设计。", deliverablesTitle: "Build with Agent 提交产物", deliverables: ["machine.bsg", "控制器代码", "telemetry / trajectory CSV", "迭代历史", "对话 / workflow 记录", "Kaggle 说明与视频"], humanTitle: "Human Boss 提交产物", humanDeliverables: ["人类建造机器", "运行记录", "Kaggle 说明与视频"], validationTitle: "第二季校验规则", validations: [{ q: "闭环证据", a: "提交记录必须展示 agent 的设计、控制器、仿真、telemetry、诊断与迭代过程。" }, { q: "控制器完整", a: "必须提交控制器，并按声明的仿真流程运行。" }, { q: "Telemetry 证据", a: "改进结论必须由有效 telemetry 和尝试记录支持。" }, { q: "禁止伪造证据", a: "不得实质性篡改机器文件、telemetry 或 workflow 记录。" }], reviewTitle: "官方复核", review: ["完整提交先进入 provisional 展示。", "获奖候选接受机器、控制器、telemetry 与 workflow 复核。", "只有 verified 作品可获得正式奖项。"], ctaRules: "查看第二季规则", ctaSubmit: "前往 Kaggle 提交" },
  leaderboard: { tag: "// 07 — 排行榜", title: "第二赛季排行榜", status: "即将开放", emptyTitle: "闭环正在预热", emptyBody: "建造、飞行、观察、改进，然后提交你最好的 verified 闭环。" },
  awards: { tag: "// 06 — 奖项", title: "第二赛季奖项", pool: { label: "第二赛季奖金池", amount: "$3,000", unit: "/ 赛季" }, main: [{ name: "第二赛季奖项", body: "奖项结构与资格以第二赛季官方 Rules 为准。", badge: "查看官方规则", prize: "待定" }], titles: [{ name: "Verified S02 Build", body: "最终认可取决于官方复核。", prize: "待定" }], community: [{ name: "第二季展示", prize: "以规则为准" }] },
  faq: { tag: "// 08 — 常见问题", title: "第二赛季 FAQ", items: [{ q: "第二季是人工驾驶吗？", a: "不是。主赛道是 agent 控制的闭环工程：agent 编写控制器、启动仿真、观察 telemetry、诊断失败、修改设计并再次尝试。" }, { q: "评分依据是什么？", a: "只有官方第二季 Rules 和正式评分器定义评分，本网站不臆造权重或公式。" }, { q: "在哪里提交？", a: "在 Kaggle 提交。本站仅作信息展示。" }] },
  cta: { title: "准备好完成\n工程闭环了吗？", button: "进入第二赛季" },
}

export const season2Content: Record<Lang, Content> = { en: merge(content.en as any, enPatch) as Content, zh: merge(content.zh as any, zhPatch) as Content }
