import { Section, SectionHeading } from "@/components/layout/Section"
import { Card } from "@/components/ui/card"
import { useI18n } from "@/i18n/I18nContext"

const EN = {
  needs: {
    tag: "// 01A — What You Need to Join",
    title: "What You Need to Join",
    intro: "To participate, you need:",
    items: [
      "Besiege base game, all participants will be gifted with a Steam activation key (please fill the form and the activation key will be sent through email).",
      "The Broken Beyond DLC.",
      "The official BuildArena 2.0 MCP configured.",
      "An AI-assisted machine built through the BuildArena 2.0 MCP, or a human-built machine for the Human BOSS Challenge.",
      "One run with a CSV trajectory file generated by BuildArena MOD.",
      "A Kaggle writeup explaining what you built and how you built it.",
    ],
    note: "A video is strongly encouraged. You do not need a polished research system to join: a simple agent workflow, a clear prompt, and a valid MCP-built machine are enough. Have fun!",
  },
  evaluation: {
    tag: "// 04A — Evaluation & Timeline",
    title: "Evaluation & Timeline",
    intro: "All dates use Anywhere on Earth (AOE, UTC−12).",
    items: [
      ["Hackathon opens", "September 20, 2026 AOE"],
      ["Submission deadline", "November 20, 2026 AOE"],
      ["Unified scoring and verification", "After the deadline"],
      ["Winners announced", "After final verification"],
    ],
    note: "All submission writeups are collected by the deadline. BuildArena then runs unified scoring and verification. The official S02 scorer and reference implementation are part of the public BuildArena 2.0 release. Multiple valid submissions are scored within each team first; the highest becomes the Effective Final Submission, and one final submission per team is rescored globally.",
  },
  videos: {
    tag: "// 05A — Videos",
    title: "Show the Run",
    body: "Videos are highly encouraged. Show the machine, the run, and the result clearly enough for the community to understand what happened. Kaggle supports YouTube links most directly; another public video link may be used when YouTube is unavailable. Simple trimming, captions, music, and commentary are welcome, but do not edit the video to materially misrepresent the scored run.",
  },
  gallery: {
    tag: "// 08A — Mission Reports & Build Gallery",
    title: "Mission Reports & Build Gallery",
    body: "BuildArena is not only about ranking machines. It is about celebrating the strange, brilliant, chaotic moment when humans and AI agents build machines together and send them toward a mission. After the hackathon, the BuildArena host will create a polished Mission Report for every valid entry and publish a public web leaderboard and build gallery.",
    note: "By submitting, participants allow the host team to feature valid entries in the mission report, leaderboard, gallery, and related community showcase materials. Participants keep ownership of their submissions.",
  },
  judges: {
    tag: "// 09A — Judges",
    title: "Judges",
    items: ["BuildArena", "Nextan Pholizebort", "Nephoslbata"],
  },
}

const ZH = {
  needs: { tag: "// 01A — 参赛准备", title: "参加比赛需要什么", intro: "参赛需要：", items: ["Besiege 本体；所有参赛者可通过官方表单获取 Steam 激活码。", "The Broken Beyond DLC。", "配置官方 BuildArena 2.0 MCP。", "通过 BuildArena 2.0 MCP 建造的 AI 机器，或 Human BOSS 挑战的人类机器。", "一条由 BuildArena MOD 生成 CSV 轨迹文件的运行记录。", "一篇说明建造内容和过程的 Kaggle writeup。"], note: "强烈鼓励提交视频。不需要完整的研究系统：简单的 agent workflow、清晰的 prompt 和有效的 MCP 机器即可。祝玩得开心！" },
  evaluation: { tag: "// 04A — 评测与时间", title: "评测与时间", intro: "所有日期均使用 Anywhere on Earth（AOE，UTC−12）。", items: [["比赛开始", "2026 年 9 月 20 日 AOE"], ["提交截止", "2026 年 11 月 20 日 AOE"], ["统一评分与验证", "截止日期之后"], ["公布获奖者", "最终验证之后"]], note: "所有 writeup 须在截止时间前提交。BuildArena 随后进行统一评分与验证；官方 S02 scorer 和 reference implementation 随公开的 BuildArena 2.0 发布。允许多次有效提交，先在队内选出 Effective Final Submission，再进行全局重算。" },
  videos: { tag: "// 05A — 视频", title: "展示运行", body: "强烈鼓励提交视频，清楚展示机器、运行过程和结果。Kaggle 最直接支持 YouTube；无法使用 YouTube 时可提交其他公开视频链接。可以简单剪辑、加字幕、音乐和解说，但不得实质性误导评分运行。" },
  gallery: { tag: "// 08A — 任务报告与机器展廊", title: "任务报告与机器展廊", body: "BuildArena 不只是排名机器，也是在庆祝人类和 AI agent 一起建造机器并完成任务的奇妙时刻。比赛结束后，BuildArena 将为每个有效作品制作任务报告，并发布公开排行榜和机器展廊。", note: "提交即表示参赛者允许主办方在任务报告、排行榜、展廊和社区展示中展示有效作品；参赛者仍保留提交物的所有权。" },
  judges: { tag: "// 09A — 评委", title: "评委", items: ["BuildArena", "Nextan Pholizebort", "Nephoslbata"] },
}

export function S02Details() {
  const { season, lang } = useI18n()
  if (season !== "s2") return null
  const d = lang === "zh" ? ZH : EN

  return (
    <>
      <Section id="requirements">
        <SectionHeading tag={d.needs.tag} title={d.needs.title} intro={d.needs.intro} />
        <Card className="gap-4 p-7">
          <ul className="grid gap-3 md:grid-cols-2">
            {d.needs.items.map((item) => <li key={item} className="border-l-2 border-crimson-bright pl-4 text-sm leading-relaxed text-cyan">{item}</li>)}
          </ul>
          <p className="border-l-2 border-ba-orange bg-secondary/20 p-4 text-sm leading-relaxed text-mist">{d.needs.note}</p>
        </Card>
      </Section>

      <Section id="evaluation">
        <SectionHeading tag={d.evaluation.tag} title={d.evaluation.title} intro={d.evaluation.intro} />
        <div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]">
          <Card className="gap-4 p-7">
            {d.evaluation.items.map(([label, value]) => <div key={label} className="flex flex-col gap-1 border-b border-white/10 pb-3 last:border-0"><span className="font-pixel text-xs uppercase tracking-widest text-ba-orange">{label}</span><span className="text-sm text-cyan">{value}</span></div>)}
          </Card>
          <Card className="p-7"><p className="text-sm leading-relaxed text-mist">{d.evaluation.note}</p></Card>
        </div>
      </Section>

      <Section id="videos">
        <SectionHeading tag={d.videos.tag} title={d.videos.title} />
        <Card className="p-7"><p className="text-sm leading-relaxed text-mist">{d.videos.body}</p></Card>
      </Section>

      <Section id="gallery">
        <SectionHeading tag={d.gallery.tag} title={d.gallery.title} />
        <Card className="gap-4 p-7"><p className="text-sm leading-relaxed text-mist">{d.gallery.body}</p><p className="border-l-2 border-ba-orange bg-secondary/20 p-4 text-sm leading-relaxed text-cyan">{d.gallery.note}</p></Card>
      </Section>

      <Section id="judges">
        <SectionHeading tag={d.judges.tag} title={d.judges.title} />
        <div className="grid gap-4 md:grid-cols-3">{d.judges.items.map((judge) => <Card key={judge} className="p-6 text-center font-pixel text-ba-orange">{judge}</Card>)}</div>
      </Section>
    </>
  )
}
